//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSaver
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditAllocation
    {
        public int Id { get; set; }
        public int CreditId { get; set; }
        public int GoalId { get; set; }
        public Nullable<decimal> AllocatedAmount { get; set; }
        public string Description { get; set; }
    
        public virtual Credit Credit { get; set; }
        public virtual SavingGoal SavingGoal { get; set; }
    }
}
